// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScheduledDate struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduledDate) Reset()         { *m = ScheduledDate{} }
func (m *ScheduledDate) String() string { return proto.CompactTextString(m) }
func (*ScheduledDate) ProtoMessage()    {}
func (*ScheduledDate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *ScheduledDate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduledDate.Unmarshal(m, b)
}
func (m *ScheduledDate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduledDate.Marshal(b, m, deterministic)
}
func (m *ScheduledDate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledDate.Merge(m, src)
}
func (m *ScheduledDate) XXX_Size() int {
	return xxx_messageInfo_ScheduledDate.Size(m)
}
func (m *ScheduledDate) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledDate.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledDate proto.InternalMessageInfo

func (m *ScheduledDate) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *ScheduledDate) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *ScheduledDate) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type Todo struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Project              string         `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Label                string         `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Description          string         `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ScheduledDate        *ScheduledDate `protobuf:"bytes,6,opt,name=scheduled_date,json=scheduledDate,proto3" json:"scheduled_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Todo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetScheduledDate() *ScheduledDate {
	if m != nil {
		return m.ScheduledDate
	}
	return nil
}

type CreateTodoRequest struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoRequest) Reset()         { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()    {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *CreateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoRequest.Unmarshal(m, b)
}
func (m *CreateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoRequest.Marshal(b, m, deterministic)
}
func (m *CreateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoRequest.Merge(m, src)
}
func (m *CreateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTodoRequest.Size(m)
}
func (m *CreateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoRequest proto.InternalMessageInfo

func (m *CreateTodoRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type CreateTodoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoResponse) Reset()         { *m = CreateTodoResponse{} }
func (m *CreateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTodoResponse) ProtoMessage()    {}
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *CreateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoResponse.Unmarshal(m, b)
}
func (m *CreateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoResponse.Marshal(b, m, deterministic)
}
func (m *CreateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoResponse.Merge(m, src)
}
func (m *CreateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTodoResponse.Size(m)
}
func (m *CreateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoResponse proto.InternalMessageInfo

type UpdateTodoRequest struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTodoRequest) Reset()         { *m = UpdateTodoRequest{} }
func (m *UpdateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoRequest) ProtoMessage()    {}
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *UpdateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoRequest.Unmarshal(m, b)
}
func (m *UpdateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoRequest.Merge(m, src)
}
func (m *UpdateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoRequest.Size(m)
}
func (m *UpdateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoRequest proto.InternalMessageInfo

func (m *UpdateTodoRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type UpdateTodoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTodoResponse) Reset()         { *m = UpdateTodoResponse{} }
func (m *UpdateTodoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoResponse) ProtoMessage()    {}
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *UpdateTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoResponse.Unmarshal(m, b)
}
func (m *UpdateTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoResponse.Merge(m, src)
}
func (m *UpdateTodoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoResponse.Size(m)
}
func (m *UpdateTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoResponse proto.InternalMessageInfo

type DeleteTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoRequest) Reset()         { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()    {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{6}
}

func (m *DeleteTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoRequest.Unmarshal(m, b)
}
func (m *DeleteTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoRequest.Merge(m, src)
}
func (m *DeleteTodoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoRequest.Size(m)
}
func (m *DeleteTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoRequest proto.InternalMessageInfo

func (m *DeleteTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteTodoResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoResponse) Reset()         { *m = DeleteTodoResponse{} }
func (m *DeleteTodoResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoResponse) ProtoMessage()    {}
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{7}
}

func (m *DeleteTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoResponse.Unmarshal(m, b)
}
func (m *DeleteTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoResponse.Merge(m, src)
}
func (m *DeleteTodoResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoResponse.Size(m)
}
func (m *DeleteTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoResponse proto.InternalMessageInfo

func (m *DeleteTodoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetTodosRequest struct {
	StartDate            *ScheduledDate `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *ScheduledDate `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetTodosRequest) Reset()         { *m = GetTodosRequest{} }
func (m *GetTodosRequest) String() string { return proto.CompactTextString(m) }
func (*GetTodosRequest) ProtoMessage()    {}
func (*GetTodosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{8}
}

func (m *GetTodosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosRequest.Unmarshal(m, b)
}
func (m *GetTodosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosRequest.Marshal(b, m, deterministic)
}
func (m *GetTodosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosRequest.Merge(m, src)
}
func (m *GetTodosRequest) XXX_Size() int {
	return xxx_messageInfo_GetTodosRequest.Size(m)
}
func (m *GetTodosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosRequest proto.InternalMessageInfo

func (m *GetTodosRequest) GetStartDate() *ScheduledDate {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *GetTodosRequest) GetEndDate() *ScheduledDate {
	if m != nil {
		return m.EndDate
	}
	return nil
}

type GetTodosResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodosResponse) Reset()         { *m = GetTodosResponse{} }
func (m *GetTodosResponse) String() string { return proto.CompactTextString(m) }
func (*GetTodosResponse) ProtoMessage()    {}
func (*GetTodosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{9}
}

func (m *GetTodosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosResponse.Unmarshal(m, b)
}
func (m *GetTodosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosResponse.Marshal(b, m, deterministic)
}
func (m *GetTodosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosResponse.Merge(m, src)
}
func (m *GetTodosResponse) XXX_Size() int {
	return xxx_messageInfo_GetTodosResponse.Size(m)
}
func (m *GetTodosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosResponse proto.InternalMessageInfo

func (m *GetTodosResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

func init() {
	proto.RegisterType((*ScheduledDate)(nil), "pb.ScheduledDate")
	proto.RegisterType((*Todo)(nil), "pb.Todo")
	proto.RegisterType((*CreateTodoRequest)(nil), "pb.CreateTodoRequest")
	proto.RegisterType((*CreateTodoResponse)(nil), "pb.CreateTodoResponse")
	proto.RegisterType((*UpdateTodoRequest)(nil), "pb.UpdateTodoRequest")
	proto.RegisterType((*UpdateTodoResponse)(nil), "pb.UpdateTodoResponse")
	proto.RegisterType((*DeleteTodoRequest)(nil), "pb.DeleteTodoRequest")
	proto.RegisterType((*DeleteTodoResponse)(nil), "pb.DeleteTodoResponse")
	proto.RegisterType((*GetTodosRequest)(nil), "pb.GetTodosRequest")
	proto.RegisterType((*GetTodosResponse)(nil), "pb.GetTodosResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 487 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0x37, 0x69, 0xe3, 0xb1, 0xd2, 0x36, 0xd3, 0x14, 0x59, 0x51, 0x85, 0x22, 0xc3,
	0xa1, 0xaa, 0x50, 0x4c, 0xc3, 0x05, 0x71, 0xa5, 0x12, 0x48, 0x5c, 0x90, 0x0b, 0x67, 0xb4, 0xc9,
	0x8e, 0x5a, 0x23, 0xe3, 0x75, 0xbd, 0xdb, 0x4a, 0x15, 0xe2, 0xc2, 0x2b, 0xf0, 0x32, 0xbc, 0x05,
	0x07, 0x5e, 0x81, 0x07, 0x41, 0x3b, 0x6b, 0x2b, 0x76, 0x4c, 0x0f, 0xdc, 0x76, 0x66, 0xff, 0xf9,
	0xb2, 0xf3, 0xff, 0x31, 0x80, 0x51, 0x52, 0x2d, 0xca, 0x4a, 0x19, 0x85, 0x7e, 0xb9, 0x9a, 0x9d,
	0x5c, 0x29, 0x75, 0x95, 0x53, 0x22, 0xca, 0x2c, 0x11, 0x45, 0xa1, 0x8c, 0x30, 0x99, 0x2a, 0xb4,
	0x53, 0xc4, 0xef, 0x60, 0x7c, 0xb9, 0xbe, 0x26, 0x79, 0x9b, 0x93, 0xbc, 0x10, 0x86, 0x10, 0x61,
	0x70, 0x4f, 0xa2, 0x8a, 0xbc, 0xb9, 0x77, 0x3a, 0x4c, 0xf9, 0x8c, 0x53, 0x18, 0x7e, 0x51, 0x85,
	0xb9, 0x8e, 0x7c, 0x6e, 0xba, 0x02, 0x0f, 0x61, 0x47, 0x8a, 0xfb, 0x68, 0x87, 0x7b, 0xf6, 0x18,
	0xff, 0xf4, 0x60, 0xf0, 0x41, 0x49, 0x85, 0xfb, 0xe0, 0x67, 0x92, 0x11, 0x41, 0xea, 0x67, 0xd2,
	0x02, 0x4c, 0x66, 0x72, 0x62, 0x40, 0x90, 0xba, 0x02, 0x23, 0xd8, 0x2b, 0x2b, 0xf5, 0x99, 0xd6,
	0x86, 0x21, 0x41, 0xda, 0x94, 0x56, 0x9f, 0x8b, 0x15, 0xe5, 0xd1, 0xc0, 0xe9, 0xb9, 0xc0, 0x39,
	0x84, 0x92, 0xf4, 0xba, 0xca, 0x4a, 0xbb, 0x41, 0x34, 0xe4, 0xbb, 0x76, 0x0b, 0x5f, 0xc2, 0xbe,
	0x6e, 0xb6, 0xf9, 0x24, 0x85, 0xa1, 0x68, 0x77, 0xee, 0x9d, 0x86, 0xcb, 0xc9, 0xa2, 0x5c, 0x2d,
	0x3a, 0x7b, 0xa6, 0x63, 0xdd, 0x2e, 0xe3, 0x73, 0x98, 0xbc, 0xae, 0x48, 0x18, 0xb2, 0xef, 0x4f,
	0xe9, 0xe6, 0x96, 0xb4, 0xc1, 0x13, 0x18, 0x58, 0x33, 0x79, 0x91, 0x70, 0x39, 0xb2, 0x10, 0xbe,
	0xe6, 0x6e, 0x3c, 0x05, 0x6c, 0x8f, 0xe8, 0x52, 0x15, 0x9a, 0x41, 0x1f, 0x4b, 0xf9, 0xbf, 0xa0,
	0xf6, 0x48, 0x0d, 0x7a, 0x02, 0x93, 0x0b, 0xca, 0xa9, 0x0b, 0xda, 0x32, 0x36, 0x7e, 0x0a, 0xd8,
	0x16, 0xb9, 0xd1, 0x9e, 0xea, 0x06, 0x0e, 0xde, 0x90, 0xb1, 0x12, 0xdd, 0x80, 0x9e, 0x03, 0x68,
	0x23, 0x2a, 0xe3, 0x5c, 0xf2, 0x1e, 0x72, 0x29, 0x60, 0x11, 0xff, 0x31, 0x9e, 0xc1, 0x88, 0x8a,
	0xda, 0x55, 0xff, 0x21, 0xfd, 0x1e, 0x15, 0xce, 0xcf, 0x25, 0x1c, 0x6e, 0x7e, 0xb2, 0x7e, 0xd6,
	0x63, 0x18, 0xda, 0x7d, 0x75, 0xe4, 0xcd, 0x77, 0x3a, 0x36, 0xb8, 0xf6, 0xf2, 0x97, 0x0f, 0xa1,
	0xad, 0x2f, 0xa9, 0xba, 0xcb, 0xd6, 0x84, 0xef, 0x01, 0x36, 0x06, 0xe3, 0xb1, 0x95, 0xf7, 0x32,
	0x9a, 0x3d, 0xda, 0x6e, 0xd7, 0xf6, 0x1d, 0x7d, 0xff, 0xfd, 0xe7, 0x87, 0x3f, 0x8e, 0x47, 0xc9,
	0xdd, 0x79, 0x62, 0xf9, 0xaf, 0xbc, 0x33, 0x4b, 0xdc, 0x38, 0xed, 0x88, 0xbd, 0xb0, 0x1c, 0xf1,
	0x1f, 0x81, 0xd4, 0xc4, 0x59, 0x87, 0x98, 0x02, 0x6c, 0x02, 0x70, 0xc4, 0x5e, 0x6a, 0x8e, 0xd8,
	0xcf, 0x29, 0x3e, 0x66, 0xe2, 0xc1, 0xd9, 0xb8, 0x21, 0x26, 0x5f, 0x33, 0xf9, 0x0d, 0xdf, 0xc2,
	0xa8, 0xf1, 0x0e, 0x8f, 0xec, 0xe8, 0x56, 0x78, 0xb3, 0x69, 0xb7, 0x59, 0xd3, 0x26, 0x4c, 0x0b,
	0x31, 0x68, 0x68, 0x7a, 0xb5, 0xcb, 0x1f, 0xf9, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdd,
	0x81, 0x25, 0xac, 0x14, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error)
	UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoResponse, error)
	DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error)
	GetTodos(ctx context.Context, in *GetTodosRequest, opts ...grpc.CallOption) (*GetTodosResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error) {
	out := new(CreateTodoResponse)
	err := c.cc.Invoke(ctx, "/pb.TodoService/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoResponse, error) {
	out := new(UpdateTodoResponse)
	err := c.cc.Invoke(ctx, "/pb.TodoService/UpdateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error) {
	out := new(DeleteTodoResponse)
	err := c.cc.Invoke(ctx, "/pb.TodoService/DeleteTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodos(ctx context.Context, in *GetTodosRequest, opts ...grpc.CallOption) (*GetTodosResponse, error) {
	out := new(GetTodosResponse)
	err := c.cc.Invoke(ctx, "/pb.TodoService/GetTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error)
	UpdateTodo(context.Context, *UpdateTodoRequest) (*UpdateTodoResponse, error)
	DeleteTodo(context.Context, *DeleteTodoRequest) (*DeleteTodoResponse, error)
	GetTodos(context.Context, *GetTodosRequest) (*GetTodosResponse, error)
}

// UnimplementedTodoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (*UnimplementedTodoServiceServer) CreateTodo(ctx context.Context, req *CreateTodoRequest) (*CreateTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodo not implemented")
}
func (*UnimplementedTodoServiceServer) UpdateTodo(ctx context.Context, req *UpdateTodoRequest) (*UpdateTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTodo not implemented")
}
func (*UnimplementedTodoServiceServer) DeleteTodo(ctx context.Context, req *DeleteTodoRequest) (*DeleteTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTodo not implemented")
}
func (*UnimplementedTodoServiceServer) GetTodos(ctx context.Context, req *GetTodosRequest) (*GetTodosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodos not implemented")
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TodoService/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TodoService/UpdateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodo(ctx, req.(*UpdateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TodoService/DeleteTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DeleteTodo(ctx, req.(*DeleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TodoService/GetTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodos(ctx, req.(*GetTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoService_CreateTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _TodoService_UpdateTodo_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _TodoService_DeleteTodo_Handler,
		},
		{
			MethodName: "GetTodos",
			Handler:    _TodoService_GetTodos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
