DROP TABLE IF EXISTS user_tokens;
DROP TABLE IF EXISTS user_passwords;
DROP TABLE IF EXISTS user_todos;
DROP TABLE IF EXISTS todo_comments;
DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
