// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/todo/todo.proto

package todo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateTodoRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Project              string   `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoRequest) Reset()         { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()    {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_168eeeae4242391a, []int{0}
}

func (m *CreateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoRequest.Unmarshal(m, b)
}
func (m *CreateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoRequest.Marshal(b, m, deterministic)
}
func (m *CreateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoRequest.Merge(m, src)
}
func (m *CreateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTodoRequest.Size(m)
}
func (m *CreateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoRequest proto.InternalMessageInfo

func (m *CreateTodoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateTodoRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *CreateTodoRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type UpdateTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	Label                string   `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTodoRequest) Reset()         { *m = UpdateTodoRequest{} }
func (m *UpdateTodoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoRequest) ProtoMessage()    {}
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_168eeeae4242391a, []int{1}
}

func (m *UpdateTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoRequest.Unmarshal(m, b)
}
func (m *UpdateTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoRequest.Merge(m, src)
}
func (m *UpdateTodoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoRequest.Size(m)
}
func (m *UpdateTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoRequest proto.InternalMessageInfo

func (m *UpdateTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTodoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateTodoRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *UpdateTodoRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type DeleteTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoRequest) Reset()         { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()    {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_168eeeae4242391a, []int{2}
}

func (m *DeleteTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoRequest.Unmarshal(m, b)
}
func (m *DeleteTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoRequest.Merge(m, src)
}
func (m *DeleteTodoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoRequest.Size(m)
}
func (m *DeleteTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoRequest proto.InternalMessageInfo

func (m *DeleteTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateTodoRequest)(nil), "todo.CreateTodoRequest")
	proto.RegisterType((*UpdateTodoRequest)(nil), "todo.UpdateTodoRequest")
	proto.RegisterType((*DeleteTodoRequest)(nil), "todo.DeleteTodoRequest")
}

func init() { proto.RegisterFile("proto/v1/todo/todo.proto", fileDescriptor_168eeeae4242391a) }

var fileDescriptor_168eeeae4242391a = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x43, 0xc1, 0xbf, 0x4b, 0xc0, 0x30, 0xfe, 0x35, 0xd5, 0x85, 0xa9, 0x1b, 0xc3, 0xa2,
	0x8d, 0xba, 0x73, 0x8b, 0xec, 0x0d, 0x48, 0xa2, 0xcb, 0x81, 0xb9, 0xe2, 0x98, 0xa1, 0xb7, 0x4e,
	0x07, 0x8c, 0x31, 0x6e, 0x7c, 0x02, 0x13, 0x1f, 0xcd, 0x57, 0xf0, 0x41, 0x4c, 0x67, 0xa8, 0x7f,
	0xa4, 0xba, 0x69, 0x7a, 0xee, 0x3d, 0xf9, 0x4e, 0xee, 0x69, 0xc1, 0x4f, 0x35, 0x19, 0x8a, 0x67,
	0x47, 0xb1, 0x21, 0x41, 0xf6, 0x11, 0xd9, 0x11, 0xab, 0xe5, 0xef, 0xc1, 0xde, 0x98, 0x68, 0xac,
	0x30, 0xe6, 0xa9, 0x8c, 0x79, 0x92, 0x90, 0xe1, 0x46, 0x52, 0x92, 0x39, 0x4f, 0xb0, 0x3b, 0xdf,
	0x5a, 0x35, 0x9c, 0x5e, 0xc7, 0x38, 0x49, 0xcd, 0x83, 0x5b, 0x86, 0x57, 0xd0, 0xea, 0x68, 0xe4,
	0x06, 0x2f, 0x48, 0x50, 0x0f, 0xef, 0xa6, 0x98, 0x19, 0xb6, 0x09, 0x4b, 0x46, 0x1a, 0x85, 0x7e,
	0x65, 0xbf, 0x72, 0xb8, 0xd6, 0x73, 0x82, 0xf9, 0xb0, 0x92, 0x6a, 0xba, 0xc5, 0x91, 0xf1, 0x3d,
	0x3b, 0x2f, 0x64, 0xee, 0x57, 0x7c, 0x88, 0xca, 0xaf, 0x3a, 0xbf, 0x15, 0xa1, 0x84, 0xd6, 0x20,
	0x15, 0xbf, 0xd0, 0x4d, 0xf0, 0xa4, 0x98, 0x73, 0x3d, 0x29, 0xbe, 0xa2, 0xbc, 0x92, 0xa8, 0x6a,
	0x49, 0x54, 0xed, 0x7b, 0xd4, 0x01, 0xb4, 0xce, 0x50, 0xe1, 0x9f, 0x51, 0xc7, 0x2f, 0x1e, 0xd4,
	0xf3, 0x7d, 0x1f, 0xf5, 0x4c, 0x8e, 0x90, 0xf5, 0x00, 0xdc, 0xe9, 0x83, 0x0c, 0x35, 0xdb, 0x89,
	0x6c, 0xad, 0x0b, 0x65, 0x04, 0xdb, 0x91, 0xeb, 0x2f, 0x2a, 0xfa, 0x8b, 0xba, 0x79, 0x7f, 0xe1,
	0xc6, 0xf3, 0xdb, 0xfb, 0xab, 0xd7, 0x08, 0x57, 0x8b, 0xef, 0x72, 0x5a, 0x69, 0xb3, 0x3e, 0xd4,
	0x3b, 0x37, 0x3c, 0x19, 0x63, 0x77, 0xc2, 0xa5, 0x2a, 0xa0, 0x0b, 0x35, 0xfc, 0x07, 0x0d, 0x7e,
	0x40, 0x2f, 0xa1, 0xe9, 0xa0, 0xe7, 0x3c, 0xcb, 0xee, 0x49, 0x8b, 0x82, 0xbb, 0x70, 0x73, 0x29,
	0x77, 0xcb, 0x72, 0xd7, 0xdb, 0x8d, 0xcf, 0x9f, 0xe8, 0x51, 0x8a, 0xa7, 0xe1, 0xb2, 0xb5, 0x9d,
	0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x7a, 0x19, 0xd7, 0x61, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	CreateUser(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangeEmail(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangePassword(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateUser(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/todo.TodoService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ChangeEmail(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/todo.TodoService/ChangeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ChangePassword(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/todo.TodoService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	CreateUser(context.Context, *CreateTodoRequest) (*empty.Empty, error)
	ChangeEmail(context.Context, *UpdateTodoRequest) (*empty.Empty, error)
	ChangePassword(context.Context, *DeleteTodoRequest) (*empty.Empty, error)
}

// UnimplementedTodoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (*UnimplementedTodoServiceServer) CreateUser(ctx context.Context, req *CreateTodoRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedTodoServiceServer) ChangeEmail(ctx context.Context, req *UpdateTodoRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEmail not implemented")
}
func (*UnimplementedTodoServiceServer) ChangePassword(ctx context.Context, req *DeleteTodoRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateUser(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/ChangeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ChangeEmail(ctx, req.(*UpdateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ChangePassword(ctx, req.(*DeleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _TodoService_CreateUser_Handler,
		},
		{
			MethodName: "ChangeEmail",
			Handler:    _TodoService_ChangeEmail_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _TodoService_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/todo/todo.proto",
}
